# use this command to run it 
# keep in mind the correct terminal path 
name: ds-c-tfod-01
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - scikit-learn
  - tensorflow
  - keras
  - opencv
  - numpy
  - tqdm
  - google-auth
  - google-auth-oauthlib
  - google-auth-httplib2
  - matplotlib
  - pillow
  - jupyter
  - nbconvert
  - nbformat
  - pip
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip:
    - "tensorflow<2.11"
    - six
    - numpy
    - wheel
    - packaging
    - keras_preprocessing
    - bash
    - opencv-python
    - wget
    - pycocotools
    - tensorflow-addons
    - pyyaml
    - tensorflow-text
